### ISSUE TITLE
tried using it, get internal server error

### ISSUE THREAD

**Issue by nikivdev** [jyothepro/snapscrape#1]
<img width="817" alt="image" src="https://github.com/user-attachments/assets/52c0f29f-bfde-4c07-9046-5c8ecb6634f7">

```
cat result.md
Internal Server Error
```

**Comment by nikivdev** [comment]
`curl 'https://snapscrape.jyothepro.com/?url=https://news.ycombinator.com' --output result.md` was command

**Comment by jyothepro** [comment]
Ya unfortunately HackNews is implementing a more sophisticated scraping bot prevention techniques. Puppeteer based scraping is not working.

I did add a try catch so you will not see the  "Internal Server Error" but it will show an error message saying the server closed the connection.

**Comment by nikivdev** [comment]
do you know a more sophisticated scraping solution that would work on hn by chance

**Comment by jyothepro** [comment]
try this - https://realpython.com/web-scraping-with-scrapy-and-mongodb/
